name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK (required for building Android)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # Cache Gradle dependencies to speed up the build
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Build the APK using Gradle
    - name: Build APK
      run: ./gradlew assembleRelease

    # Upload APK as artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: app/build/outputs/apk/release/app-release.apk





