name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Remove Old Gradle
      run: rm -rf ~/.gradle/wrapper/dists/

    - name: Download and Upgrade Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -O gradle.zip
        unzip gradle.zip
        mv gradle-7.5.1 gradle
        echo "$PWD/gradle/bin" >> $GITHUB_PATH

    - name: Set executable permissions for Gradle Wrapper
      run: chmod +x ./gradlew
      working-directory: AndroidKeylogger

    - name: Force Update Gradle Wrapper
      run: ./gradlew wrapper --gradle-version 7.5.1 --distribution-type all
      working-directory: AndroidKeylogger

    - name: Build APK
      run: ./gradlew assembleDebug
      working-directory: AndroidKeylogger

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: AndroidKeylogger/app/build/outputs/apk/debug/app-debug.apk




